In [35]:
pip install xgboost

Requirement already satisfied: xgboost in c:\coding\python.app\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\coding\python.app\lib\site-packages (from xgboost) (2.3.0)
Requirement already satisfied: scipy in c:\coding\python.app\lib\site-packages (from xgboost) (1.16.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
#installing required libraries
import xgboost as xgb
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, average_precision_score,confusion_matrix

In [4]:
datav2 =pd.read_csv(r"C:\Users\vishw\Desktop\projects\mini projects aiml\credit_card\creditcard.csv")
datav2

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [38]:
datav2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [39]:
datav2.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.175161e-15,3.384974e-16,-1.379537e-15,2.094852e-15,1.021879e-15,1.494498e-15,-5.620335e-16,1.149614e-16,-2.414189e-15,...,1.628620e-16,-3.576577e-16,2.618565e-16,4.473914e-15,5.109395e-16,1.686100e-15,-3.661401e-16,-1.227452e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [40]:
#removing duplicates and unnamed column 
if 'Unnamed:0' in datav2.columns:
    datav2.drop("Unnamed",axis=1,inplace=True)
#removing true beahivourial duplicates
initial_rows = datav2.shape[0]
subset = [c for c in datav2.columns if c not in ['Time', 'Class']]
datav2.drop_duplicates(subset=subset, inplace=True)
print(f"🧹 Removed {initial_rows - datav2.shape[0]} true duplicate transactions.")

print(f"✅ Data Cleaned. Current Shape: {datav2.shape}")

🧹 Removed 9144 true duplicate transactions.
✅ Data Cleaned. Current Shape: (275663, 31)

behaviourial duplication and why remvoing time column eliminates it: This allowed the model to find the 8,063 rows where a fraudster (or a system glitch) tried the exact same transaction multiple times at different seconds.

subset = [c for c in datav2.columns if c not in ['Time', 'Class']], here second c is a temporary name for new column where all the columns from datav2 except time and class will be stored , the first c is used for looping through the columns and temporary naming each column that passes the condition as c

In [41]:
#feature engineering
#Transforming raw columns into signals that XGBoost can interpret more effectively.

print("feature 1:: HOUR OF DAY.." )
#converting Time column to hour of day 
#converting seconds into hours
datav2['Hour_of_day']=(datav2 ['Time']//3600) %24 #this is linear hour ,while it does help it does not tell the model about the cyclic nature of hours


#creating is night feature to flag transactions happening between 6 am to 11pm
print("feature 2:: RISKY TIME FLAG...")
datav2['Is_night']=datav2['Hour_of_day'].apply(lambda x:1 if x<=6 or x>=23  else 0) #this creates and checks time window of whether the fraud occured between 11pm to 6 am
print("feature 3:: LOG AMOUNT...")
# converting Amount to log Amount 
datav2['log_amount']=np.log1p(datav2['Amount'])   #it converts transaction amount to logs to minimize the difference between them say 12000rs and 40 rs so absically we squash the values to shorten them
#dropping original Time column to prevent confusion
datav2.drop('Time',axis=1,inplace=True)

feature 1:: HOUR OF DAY..
feature 2:: RISKY TIME FLAG...
feature 3:: LOG AMOUNT...

The Question: When we transform Amount to log, why do we keep it in Block 2 but drop it in Block 3?

The Strategy: We need Amount for Financial ROI, but we don't want it for Feature Training.
Block 2 (Feature Engineering): We create Log_Amount. We keep the original Amount here because the X and y variables are still being defined.
The "Photocopy" Step: test_amounts = X_test['Amount'].values. We save the "Real Dollars" into a separate variable. This is critical because you cannot report success in "Log-Dollars." If you catch a thief, you want to tell your boss you saved $5,000, not 8.5 Log-units.

Question: why do use log1p intead of log 0 
sol:  bcoz many credit card amounts can be 0.00$ and applying log 0 to 0 value might result in crash , applying log1p adds 1 to the value making sure that its nevel null.

In [42]:
datav2.tail()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V24,V25,V26,V27,V28,Amount,Class,Hour_of_day,Is_night,log_amount
284802,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,...,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0,23.0,1,0.570980
284803,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,...,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0,23.0,1,3.249987
284804,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,...,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0,23.0,1,4.232366
284805,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,...,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0,23.0,1,2.397895
284806,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,...,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0,23.0,1,5.384495

In [43]:
datav2.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V24,V25,V26,V27,V28,Amount,Class,Hour_of_day,Is_night,log_amount
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0,0.0,1,5.014760
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0,0.0,1,1.305626
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0,0.0,1,5.939276
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0,0.0,1,4.824306
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0,0.0,1,4.262539

In [44]:
#separating features and target
x=datav2.drop('Class',axis=1)
y=datav2["Class"]

In [45]:
#splitting and scaling
#using stratified split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [46]:
#saving original amount from test set before scaling it for future calculations
amount_test=x_test['Amount'].values
#removing previous amount column
x_train.drop('Amount',axis=1,inplace=True)
x_test.drop('Amount',axis=1,inplace=True)

In [47]:
#scaling using standard scaler
scaler=StandardScaler()
x_train_scaled=pd.DataFrame(scaler.fit_transform(x_train),columns=x_train.columns)
x_test_scaled=pd.DataFrame(scaler.transform(x_test),columns=x_test.columns)
print("data scaled successfully")

data scaled successfully

In [48]:
#applying and training xgboost 
#checking the Class distribution of the dataset
fraud_weight=len(y_train[y_train==0]) / len(y_train[y_train==1])#this is used further by the model to understand about the class imbalance and treat every fraud with more caution
print(f"training complete ,(fraud weight:{fraud_weight:.2f})..")
#training the v2 model
v2_baseline_model=xgb.XGBClassifier(
    n_estimators=200,
    random_state=42,
    max_depth=5,
    learning_rate=0.05,#xgboost builds upon previous tree and tries to fix the mistakes of previous tree, learning rate tells how much the current tree trusts the previous tree also called as shrinkage
    scale_pos_weight=fraud_weight,
    n_jobs=-1,
    eval_metric='aucpr'

)
v2_baseline_model.fit(x_train_scaled,y_train)
print("v2 model trained")

training complete ,(fraud weight:582.41)..
v2 model trained

learning rate: xgboost builds upon previous trees, the first tree is generally more conservative and only provides low level risks say 10 percent, the second tree takes the input of first tree and applies learning rate combined with its own result it tries to fix the error or imprve the residual (actual value - predicted value), new prediction= old prediction+(learning rate * new predicition)means the 2nd tree will only consider say 0.1 percent of previous tree's result, this prevents overfitting and prevents biasness of one tree if previous one was biased

scale_pos_weight: it tells the model to focus more on the provided attribute

In [49]:
#predicitons and results
test_pred=v2_baseline_model.predict(x_test_scaled)
test_prob=v2_baseline_model.predict_proba(x_test_scaled)[:, 1]
#confusion matrix
true_neg,false_pos,false_neg,true_pos=confusion_matrix(y_test , test_pred).ravel()

#calculating the success metric ( AUPRC)
aup_score= average_precision_score(y_test, test_prob)#the average_precision_score is a function in scikit learning that calculates the auprc at every point ranging between 0 to 1,the closer the score to 1 the better the results

In [50]:
#amount saved from fraud
amount_saved=amount_test[(y_test==1) & (test_pred==1)].sum()
false_alarm_cost=false_pos * 5 # $5 for every innocent customer blocked 
net_roi=amount_saved - false_alarm_cost

In [51]:
#FINAL BREAKDOWN OF BASELINE MODEL
print(f"SAVED COST ${amount_saved:,.2f}")
print(f"CUSTOMER ANNOYANCE COST${false_alarm_cost:,.2f}( {false_pos} false alarms)")
print(f"AUPRC SCORE {aup_score:,.4f}")
print(f"NET ROI ${net_roi:,.2f}")

SAVED COST $10,187.41
CUSTOMER ANNOYANCE COST$225.00( 45 false alarms)
AUPRC SCORE 0.8044
NET ROI $9,962.41

In [52]:
import os

In [53]:
from datetime import datetime

timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
filename = f"model_{timestamp}.pkl"
print(filename) # Output: model_2026-04-11_15-45.pkl

model_2026-04-11_16-11.pkl

In [54]:
#BASELINE MODEL MLOPS PIPELINING , CREATING AUTOMATED CHECKS,EXPERIMENT TRACKING
health_status= "HEALTHY"

#The safety guardrail
if aup_score < 0.70:
    health_status="DEGRADED (LOW PRECISION)"
    print( " ⚠️ WARNING... AREA PRECISION SCORE TOO LOW")
elif false_pos >(len(y_test)*0.5):
    health_status="DEGRADED (HIGH ANNOYANCE COST)"
    print("⚠️ WARNING... TOO MANY ANNOYED CUSTOMERS")

#experiment tracking( file name where the model hyperparemeters will be saved)
log_file="experiment_tracking.csv"

#saving the hyperparameters
run_data = {
    "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    "Model": "XGBoost V2.0",
    "n_estimators": 200,
    "max_depth": 5,
    "learning_rate": 0.05,
    "AUPRC": round(aup_score, 4),
    "True_Positives": true_pos,
    "False_Positives": false_pos,
    "Net_ROI_USD": round(net_roi, 2),
    "Health_Status": health_status
}
#dictionary to dataframe
tracker_df = pd.DataFrame([run_data]) #it temporary stores the hyperparameters in dictionary format and converts it into dataframe so that it can be  stored in log_file
if not os.path.exists(log_file):
    tracker_df.to_csv(log_file, index=False)
else:
    tracker_df.to_csv(log_file, mode='a', header=False, index=False)

In [55]:
#saving the model and scaler
joblib.dump(v2_baseline_model, 'v2_xgboost_baseline_model.joblib')
joblib.dump(scaler, 'v2_scaler.joblib')

['v2_scaler.joblib']

In [ ]:
#upgraded version

creating a newly trained model that fixes problems with the baseline model and log it in the mlops